import { Stamp } from '../../types';

export const TOKYO_STAMPS: Omit<Stamp, 'completed' | 'completedAt'>[] = [
  {
    id: 'shibuya-crossing',
    title: 'Cross Shibuya Crossing',
    description: 'The world\'s busiest pedestrian crossing — controlled chaos',
    neighborhood: 'Shibuya',
    category: 'iconic',
    bestTime: 'evening',
    tip: 'Watch from Starbucks above for the full effect first, then cross it yourself',
  },
  {
    id: 'sensoji-morning',
    title: 'Senso-ji at Dawn',
    description: 'Tokyo\'s oldest temple, before the crowds arrive',
    neighborhood: 'Asakusa',
    category: 'culture',
    bestTime: 'morning',
    tip: 'Arrive by 6am. The lanterns are lit, the incense is burning, almost no one around',
  },
  {
    id: 'standing-ramen',
    title: 'Eat Standing Ramen',
    description: 'Slurp noodles at a tiny standing counter like a local',
    neighborhood: 'Various',
    category: 'food',
    tip: 'Look for spots with just a counter and no seats. Faster, cheaper, more authentic',
  },
  {
    id: 'golden-gai',
    title: 'Drink in Golden Gai',
    description: '6 narrow alleys, 200+ tiny bars, pure Tokyo magic',
    neighborhood: 'Shinjuku',
    category: 'nightlife',
    bestTime: 'night',
    tip: 'Most bars seat 5-7 people. Cover charges exist. Just pick one and go in',
  },
  {
    id: 'meiji-shrine',
    title: 'Walk Through Meiji Shrine Forest',
    description: 'A forest in the middle of Tokyo, leading to a peaceful shrine',
    neighborhood: 'Harajuku',
    category: 'nature',
    bestTime: 'morning',
    tip: 'Enter from Harajuku side. The 10-minute walk through trees is the point',
  },
  {
    id: 'skytree-view',
    title: 'See Tokyo from Above',
    description: 'Tokyo Skytree or Tokyo Tower — the sprawl is unreal',
    neighborhood: 'Sumida / Minato',
    category: 'iconic',
    bestTime: 'evening',
    tip: 'Go 30min before sunset. Watch the city light up',
  },
  {
    id: 'tsukiji-morning',
    title: 'Morning at Tsukiji Outer Market',
    description: 'The inner market moved, but the food stalls remain',
    neighborhood: 'Tsukiji',
    category: 'food',
    bestTime: 'morning',
    tip: 'Go hungry around 9am. Eat tamagoyaki, fresh sashimi, whatever looks good',
  },
  {
    id: 'omoide-yokocho',
    title: 'Get Lost in Omoide Yokocho',
    description: 'Smoky alley of yakitori joints under the tracks',
    neighborhood: 'Shinjuku',
    category: 'food',
    bestTime: 'evening',
    tip: 'Also called "Piss Alley." Tiny seats, grilled meat, cold beer. Point at what looks good',
  },
  {
    id: 'konbini-feast',
    title: 'Have a Konbini Feast',
    description: 'Japanese convenience stores are actually incredible',
    neighborhood: 'Anywhere',
    category: 'food',
    tip: 'Onigiri, egg sandwiches, fried chicken, strong zero. Budget meal that\'s actually good',
  },
  {
    id: 'akihabara',
    title: 'Experience Akihabara',
    description: 'Electronics, anime, arcades, maid cafes — sensory overload',
    neighborhood: 'Akihabara',
    category: 'iconic',
    tip: 'Even if you\'re not into anime, the multi-floor arcades are worth it',
  },
  {
    id: 'yanaka-cats',
    title: 'Find Cats in Yanaka',
    description: 'Old Tokyo neighborhood famous for temple cats',
    neighborhood: 'Yanaka',
    category: 'nature',
    bestTime: 'morning',
    tip: 'Wander Yanaka Cemetery and the surrounding streets. Cats are everywhere',
  },
  {
    id: 'depachika',
    title: 'Explore a Department Store Basement',
    description: 'Underground food halls with free samples and beautiful food',
    neighborhood: 'Various',
    category: 'food',
    tip: 'Shinjuku Isetan or Ginza Mitsukoshi. Go hungry. Try everything',
  },
  {
    id: 'teamlab',
    title: 'Get Lost in teamLab',
    description: 'Immersive digital art that you walk through',
    neighborhood: 'Odaiba / Azabudai',
    category: 'culture',
    tip: 'Book tickets in advance. Wear shorts — some rooms have water',
  },
  {
    id: 'yoyogi-sunday',
    title: 'Sunday at Yoyogi Park',
    description: 'Rockabilly dancers, picnics, street performers',
    neighborhood: 'Harajuku',
    category: 'culture',
    bestTime: 'afternoon',
    tip: 'Only on Sundays. The rockabilly dancers near the entrance are legendary',
  },
  {
    id: 'onsen',
    title: 'Take an Onsen Bath',
    description: 'Japanese hot spring bathing — intimidating, then amazing',
    neighborhood: 'Various',
    category: 'culture',
    tip: 'Follow the rules: shower first, no swimsuits, towel on head not in water. Then relax',
  },
];
